// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@typebot.io/forge'
import { assignChatBlock } from '.'
import { auth } from './auth'

export const assignChatBlockSchema = parseBlockSchema(assignChatBlock)
export const assignChatCredentialsSchema = parseBlockCredentials(
  assignChatBlock.id,
  auth.schema
)
