name: Deploy Apps to Dev Environment

on:
  pull_request:
    types: [closed]
    branches:
      - development
  workflow_dispatch:

jobs:
  build-and-deploy:
    env:
      DATABASE_URL: 'postgresql://'
    strategy:
      matrix:
        app: ['builder', 'viewer']
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and tag Docker image
        run: |
          docker build --build-arg "SCOPE=${{ matrix.app }}" -t twerlo/typebot-${{ matrix.app }}:dev .

      - name: Push Docker image to Docker Hub
        run: docker push twerlo/typebot-${{ matrix.app }}:dev
